### ISSUE TITLE
CM 3 / Contao 5 - Spalten in Elementübersicht werden dargestellt, obwohl abgewählt

### ISSUE THREAD

**Issue by vossmedien** [alnv/contao-catalog-manager-bundle#24]
Derzeit habe ich das Problem, dass in der Übersicht der Datensätze teilweise Felder angezeigt werden, obwohl sie gar nicht angezeigt werden sollten (also abgewählt sind). Vor allem "Sortierindex" und "ID" sind hier das Problem. Wenn ich diese Felder dann zusätzlich noch zur Ansicht auswähle, entstehen leere Spalten. Das Verhalten wirkt hier noch sehr buggy, da es bei einem anderen Catalog besser funktioniert und hier nur Felder dargestellt werden, die eingestellt sind.

**Comment by alnv** [comment]
Das kann ich nicht reproduzieren, benötige mehr Infos zur Konfiguration.

**Comment by vossmedien** [comment]
Erst einmal danke für die Rückmeldung! Ich wollte dir gerade ein Video aufnehmen um es zu demonstrieren aber der Fehler tritt nun tatsächlich nicht mehr auf - das an und abwählen der Spalten und der Sortierung funktioniert problemlos und das abwählen hinterlässt auch keine leeren Spalten mehr. Falls es nochmal auftritt, melde ich mich. Danke!
