### ISSUE TITLE
CM 3 / Contao 5 - Feld: Upload, Typ: Gallery - Sortierung der Bilder nicht möglich

### ISSUE THREAD

**Issue by vossmedien** [alnv/contao-catalog-manager-bundle#25]
Ich würde gerne an einem Katalog ein Gallery-Feld hinzufügen und deren Bilder wie im restlichen CMS sortieren können, ich meine das ging auch in der Vergangenheit :)

Es ist zwar auch das Feld orderSRC verfügbar aber es sieht nicht danach aus, das mir das hier hilft.

Gibt es hier bereits eine Möglichkeit, die ich übersehe oder muss das noch implementiert werden?

Danke!

**Comment by alnv** [comment]
Ab v3.0.17 sollte die Sortierung automatisch kommen. Ein zusätzliches Feld "orderSRC" ist nicht mehr notwendig.

**Comment by vossmedien** [comment]
Vielen Dank!
