### ISSUE TITLE
CM 3 / Contao 5 - Benutzerrechte funktionieren nicht?

### ISSUE THREAD

**Issue by vossmedien** [alnv/contao-catalog-manager-bundle#26]
Ich habe eine Benutzergruppe "Redakteur" die eigentlich sämtliche Rechte zum Bearbeiten des Catalogs zur Verfügung stehen sollten.

Diese sind für den Redakteur auch im Backend sichtbar, allerdings kann er keine neuen anlegen und möchte man "in" den Datensatz wechseln, kommt:

**Was ist das Problem?
Not enough permissions to update [Subject: Source: catalog_name; ID: 1].**

Ein-& Ausblenden ist auch nicht sichtbar.
Kann hier noch etwas an anderer Stelle eingestellt werden? (Habe am Catalog usw. nichts gefunden) oder ist das derzeit noch nicht implementiert?

Danke!

**Comment by alnv** [comment]
Benutzerrechte sind noch nicht implementiert.

**Comment by vossmedien** [comment]
Hey @alnv danke dir für die Rückmeldung. Dann muss ich wenigstens nicht mehr suchen :-)
Gibt es einen ungefähren Zeitrahmen für die Implementierung? Lieben Dank für die tolle Arbeit!

**Comment by alnv** [comment]
Danke, noch nicht … aber es ist einer der wichtigen Features die zeitnah kommen werden

**Comment by vossmedien** [comment]
Funktioniert nun!
