### ISSUE TITLE
CM 3 / Contao 5 - "Verbindungen" zu anderen Tabellen & Ausgabe des ausgewählten Datensatzes auf Detailseite

### ISSUE THREAD

**Issue by vossmedien** [alnv/contao-catalog-manager-bundle#27]
Ich habe 2 Kataloge:

- Ansprechpartner
- Beiträge

Innerhalb der Beiträge, habe ich ein Select-Feld, aus der ich die Ansprechpartner auswählen kann:
![Bildschirmfoto 2024-06-04 um 19 18 38](https://github.com/alnv/contao-catalog-manager-bundle/assets/13534431/b8d1b260-037f-4a67-a6fb-d111795adaf4)
![Bildschirmfoto 2024-06-04 um 19 18 30](https://github.com/alnv/contao-catalog-manager-bundle/assets/13534431/c659d502-104c-4a13-bb70-9e2b40bce133)

Das funktioniert auch soweit, allerdings wird auf der Detailseite lediglich die ID und der Name ausgegeben.
In der alten Version konnte ich hier auf sämtliche Daten zugreifen. (Glaube ich :-))

Übersehe ich hier etwas oder ist das noch nicht implementiert? Dieses Feature ist leider sehr wichtig für die Umsetzung, evtl. kannst du uns hier kurz Feedback geben.

Vielen Dank!

**Comment by vossmedien** [comment]
Ich habe einen Weg gefunden über ein Extra Listenmodul auf der Detailseite und dem Filter
FIND_IN_SET und dem jeweiligen Inserttag {{MASTER::ansprechpartner}}
Hier gibt es nur ein Problem. Wenn mehrere Ansprechpartner ausgewählt werden, wird nur der erste Datensatz angezeigt. Ich habe hier leider auch keine Möglichkeit an die IDs zu kommen um beispielsweise die ID s zu nutzen. (oder?) 

Ich könnte zwar rein die ID s in die Datenbank speichern, allerdings sieht so der Redakteur auch bei der Auswahl nur die IDs und nicht mehr die entsprechenden Namen.

**Comment by vossmedien** [comment]
Update. So wie es aussieht, liegt es an dem Leerzeichen zwischen dem Komma und den nächsten Namen. Gibt es einen Weg, dieses zu entfernen?

**Comment by alnv** [comment]
Du brauchst keine eigene Liste … im Template kannst du die getRelated Funktion verwenden, um auf andere Tabellen zuzugreifen:

``` php
// cm_master_* 
$arrData = $this->getRelated('ansprechpartner');
dd($arrData);
```

Und wegen dem Master Insert tag:
{{MASTER::origin>ansprechpartner}}
{{MASTER::getRelated>ansprechpartner>id}}
Damit kommst du an die Werte, die du für den Filter benötigst.

**Comment by vossmedien** [comment]
Spitze. Das hat geklappt, danke!

**Comment by asaage** [comment]
Verständnissfrage:
Wie mache ich das, wenn ich eine Kindtabelle angelegt habe?
Mit  ```$this->getRelated('fieldname'); ``` komm ich nicht weiter, da 'fieldname' in der Elterntabelle erwartet wird - ich hab aber nur ein 'pid' Feld in der Kindtabelle. Fehlt sowas wie ```$this->getItems('from_childtable'); ``` oder überseh' ich was?

**Comment by asaage** [comment]
👍🏼 Das hat geholfen:
https://github.com/alnv/contao-catalog-manager-bundle/blob/master/README.md?plain=1#L261-L280

**Comment by grummbeer** [comment]
Hi @asaage, würdest Du mir verraten, was denn in den von Dir verlinkten Zeilen stand? Scheint sicht geändert zu haben und ich kann auch in der Historie der README die Zeilen nicht finden.

Danke!

**Comment by grummbeer** [comment]
@asaage  Ach … 23 Juni 2024 nicht juni 2023 :-)

`new Listing()` funktioniert.

**Comment by asaage** [comment]
Ich meinte das hier: https://github.com/alnv/contao-catalog-manager-bundle/tree/master#listen-mit-php

**Comment by grummbeer** [comment]
Danke, das funktioniert.
