### ISSUE TITLE
CM 3 / Contao 5 - GeoCoding

### ISSUE THREAD

**Issue by rustykowski** [alnv/contao-catalog-manager-bundle#33]
Soll in Version 3 das Geocoding schon funktionieren? 
In den Einstellungen des Katalogs gibt es dazu nur eine Checkbox, keine Auswahl von Adressfeldern oder ähnlich.

Beim Speichern eines Datensatzes erhalte ich allerdings folgende Fehlermeldung:

Internal Server Error
HTTP/2 400 returned for "https://maps.googleapis.com/maps/api/geocode/json?address=&key=[meinApiKey]&language=de&region=de".

Und folgerichtig beim Aufruf des Requests folgenden Fehler:
```
{
   "error_message" : "Invalid request. Missing the 'address', 'components', 'latlng' or 'place_id' parameter.",
   "results" : [],
   "status" : "INVALID_REQUEST"
}
```

**Comment by alnv** [comment]
Mehr Infos: https://github.com/alnv/contao-catalog-manager-bundle?tab=readme-ov-file#umkreissuche-einrichten

**Comment by rustykowski** [comment]
Danke! mit der Rolle „street“ klappt es prima. 
(Die Rolle „city“ führte zu einer Begrenzung des Feldes auf varchar(128).)
