### ISSUE TITLE
Breadcrumb. `pageTitle` der Seite mit Modul "Detailansicht" wird nicht zurückgesetzt.

### ISSUE THREAD

**Issue by grummbeer** [alnv/contao-catalog-manager-bundle#38]
Wenn auf einer Seite die Detailansicht gezeigt wird, fügt sich in der breadcrumb der Eintrag für das Katalog-Element ein. Die Contao-Seite mit dem Modul hat nun den Titel der Katalog-Entität.

Seiten:

- Reisen
  - Island (Seite mit Listung und Detail)

Breadcrumb

- Reisen (pageTitle: "Schöne Reisen")
   - Island (pageTitle: "Reisen nach Island") 

Wird jetzt ein Katalog-Elmente aufgerufen sieht die breadcrumb so aus:

- Reisen (pageTitle: "Schöne Reisen")
   - Island (pageTitle: "10 Tage Rundreise")  **pageTitle wie Eintrag aus Katalog**
     - 10 Tage Rundreise (pageTitle: "10 Tage Rundreise")

Der Titel der Seite "Island" wurde hier https://github.com/alnv/contao-catalog-manager-bundle/blob/4df2f7f98c8eeee27715bef327c266058981a6cd/src/EventListener/GeneratePageListener.php#L26

mit den Daten aus dem Katalog überschrieben, aber hier, beim Einfügen des letzten Elementes in die Breadcrumb nicht wieder herstellst.

https://github.com/alnv/contao-catalog-manager-bundle/blob/4df2f7f98c8eeee27715bef327c266058981a6cd/src/EventListener/GenerateBreadcrumbListener.php#L63

Es sieht so aus, als sollte hier, neben dem URL auch der `pageTitle` wiederhergestellt werden.

```php
if (($objPage = PageModel::findByPk($strPageId)) && !$blnRequireItem) {
      try {
          $arrItem['href'] = $objPage->getFrontendUrl();
          $arrItem['title'] = $objPage->pageTitle;
       // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      } catch (\Exception $objError) {
          //
      }
  }
```

**Comment by grummbeer** [comment]
@alnv wenn das bestätigt ist und mein Lössungsvorschlag passend ist, würde ich eine PR dafür einreichen.

**Comment by alnv** [comment]
Ich werde es die kommende Tage kontrollieren …

**Comment by grummbeer** [comment]
Danke, vielleicht auch noch den Schlüssel `isRoot` für das Katalog-Element hinzufügen.

Der Wert sollte vermutlich immer `false` sein, da er ja hinten drangenhängt wird.

```php
$arrItem['isRoot'] = false;
```

**Comment by alnv** [comment]
Danke … wir werden es in die v3.2 packen.

**Comment by grummbeer** [comment]
Vielen Dank!
