### ISSUE TITLE
Rolle "description" für die meta description verwenden?

### ISSUE THREAD

**Issue by grummbeer** [alnv/contao-catalog-manager-bundle#40]
Aktuell wird ja die Rolle "teaser" als meta decription benutzt. 

https://github.com/alnv/contao-catalog-manager-bundle/blob/4df2f7f98c8eeee27715bef327c266058981a6cd/src/EventListener/GetPageLayoutListener.php#L71-L72

Irgendwie macht es zwar Sinn, da praktisch ein kurzer Anrisstext damit gemeint ist, der natürlich auch für die meta decription taugt. Allerdings benutzt man intuitiv die Rolle "description" anlaog zur Rolle "titel", die ja bereits für den meta title benutzt wird.

"teaser" bringt man eher mit der, im dropdown direkt darunter aufgeführten, Rolle "content" in Verbindung.

Vielleicht lässt sich das verbessern.

**Comment by alnv** [comment]
Ab v3.2 wird es extra dafür neue Rollen geben (MetaTitle und MetaDescription).

**Comment by grummbeer** [comment]
Perfekt gelöst! Danke.
